### ISSUE TITLE
Conga 5090 workMode 38

### ISSUE THREAD

**Issue by miguelangel-nubla** [adrigzr/agnoc#41]
Hi, using Congatudo on a 5090 and I am running into an exception when cleaning finished.
The addon crashes with this traceback.
```
[2022-01-23T12:34:57.600Z] [ERROR] Uncaught Exception {
  err: DomainException: Unable to map device state from data: {"type":3,"workMode":38,"chargeStatus":false}
      at getDomainValue (/snapshot/app/node_modules/@agnoc/core/lib/mappers/device-state.mapper.js:53:9)
      at Function.toDomain (/snapshot/app/node_modules/@agnoc/core/lib/mappers/device-state.mapper.js:59:14)
      at Robot.handleDeviceStatus (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:861:60)
      at Robot.handleMessage (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1144:7)
      at CloudServer.handleMessage (/snapshot/app/node_modules/@agnoc/core/lib/emitters/cloud-server.emitter.js:135:13)
      at Connection.<anonymous> (/snapshot/app/node_modules/@agnoc/core/lib/emitters/cloud-server.emitter.js:154:12)
      at Connection.emit (node:events:406:35)
      at Connection.handlePacket (/snapshot/app/node_modules/@agnoc/core/lib/emitters/connection.emitter.js:114:10)
      at PacketSocket.emit (node:events:394:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at PacketSocket.Readable.push (node:internal/streams/readable:228:10)
      at PacketSocket.onReadable (/snapshot/app/node_modules/@agnoc/core/lib/sockets/packet.socket.js:130:27)
      at processImmediate (node:internal/timers:464:21) {
    metadata: undefined
  },
  origin: 'uncaughtException'
}
```

Seems workMode 38 is not defined.

**Comment by miguelangel-nubla** [comment]
https://github.com/adrigzr/agnoc/pull/42

**Comment by adrigzr** [comment]
@miguelangel-nubla thanks for the issue. Merging as soon as it passes CI.

**Comment by adrigzr** [comment]
Merged in `next` branch.
